/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge18;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        FizzBuzz binarySearchTree = new FizzBuzz();
        Node root = new Node(8);
        root.left = new Node(6);
        root.left.left = new Node(7);
        root.right = new Node(10);
        root.right.right = new Node(31);
        root.right.left = new Node(15);
        root.left.right=new Node(12);
        binarySearchTree.fizzBuzz(root);
    }
}