/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge28;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int[] arr = { 8,4,23,42,16,15};
        int n = arr.length;
        QuickSort quickSort1= new QuickSort();
       quickSort1.quickSort(arr, 0, n - 1);
        System.out.print("sorted Array: ");
      quickSort1.printArray(arr , arr.length);
    }
}
