/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge05;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        LinkedList list = new LinkedList();
        list.insert(9);
        list.insert(7);
        list.insert(8);

        list.includes(8);
        System.out.println(list.tostring());

    }


}
