/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge18;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void fizzBuzz(){
        FizzBuzz binarySearchTree = new FizzBuzz();
        Node root = new Node(8);
        root.left = new Node(6);
        root.left.left = new Node(7);
        root.right = new Node(10);
        root.right.right = new Node(31);
        List<String> list = new ArrayList<>();
        list.add("8");
        list.add("Fizz");
        list.add("Buzz");
        list.add("7");
        list.add("31");

        assertEquals(list , binarySearchTree.fizzBuzz(root));
    }

}
