/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge05;

import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {

        System.out.println(new App().getGreeting());

        LinkedList list = new LinkedList();
        list.append(9);
        list.append(7);
        list.append(8);
        list.append(21);

        list.includes(8);
        list.append(4);
        list.append(100);
        list.insert(1);
        list.insert(1);
        list.insertBefore(7, 14);


        System.out.println(list.insertAfterValue(7,31));
        list.kthFromEnd(10);
        System.out.println(list.tostring());
//*******************************************************************************************

        LinkedList list1 =new LinkedList();
        list1.append(2);
        list1.append(5);
        list1.append(8);
        LinkedList list2=new LinkedList();
        list2.append(10);
        list2.append(20);
        list2.append(30);

//        LinkedList.zip_lists(list1,list2);


    }


}
