/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge05;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void linkedListTest(){ // You should change the type of output to (int) for this test

        LinkedList list = new LinkedList();
        list.insert(9);
        int value1 = 9;
        assertEquals(value1, list.insert(9) );
         }
    @Test public void linkedListTest2(){
        LinkedList list = new LinkedList();
        list.insert(9);
        int value = 8;
        boolean value2= false;
        assertEquals(value2, list.includes(value));
}
    @Test public void linkedListTest3(){
        LinkedList list = new LinkedList();
        list.insert(9);
        String value2= "{ 9 } -> NULL";
        assertEquals(value2, list.tostring());

}}
