/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge15;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void add_contain_BinarySearch(){
        BinarySearchTree tree = new BinarySearchTree();
        tree.add(5);
        tree.add(8);
        tree.add(9);
        assertEquals( 3, tree.add(3));
        assertEquals( 5, tree.add(5));

        assertEquals(true , tree.contains(5));
        assertEquals(false , tree.contains(6));
        assertEquals(true , tree.contains(8));
    }

    @Test
    public void BinaryTree() {
        BinaryTree binaryTree = new BinaryTree();
        Node root = new Node(10);
        Node root1 = new Node(24);
        Node root3 = null;

      assertEquals( true ,binaryTree.pre_Order(root));
      assertEquals( false ,binaryTree.pre_Order(root3));

      assertEquals(false ,binaryTree.in_Order(root3) );
      assertEquals(true ,binaryTree.in_Order(root));

        ArrayList list = new ArrayList();
        list.add(24);
        list.add(10);
        binaryTree.post_Order(root1);
        assertEquals( list , binaryTree.post_Order(root));

    }

}
