/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge15;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

     double studentGPA= 3.63;
     String studentName = "Ibrahim";
     String lastName = "Alhamshari";

        System.out.println(studentName+" "+ lastName +" has GPA: " + studentGPA);

        Scanner input = new Scanner(System.in);
       studentGPA= input.nextDouble();

        System.out.println(studentName+" "+ lastName +" has a new GPA: " + studentGPA);
    }
}