/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge03;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        int[] arr ={1,3,4,5,6,8,9,10};
        int number=3;
        runBinarySearchIteratively(arr , number);
    }

    public static int runBinarySearchIteratively(int[] sortedArray, int key) {
        int low=sortedArray[0];
        int high=sortedArray[sortedArray.length-1];
        int index = 0;

        while (low <= high) {
            int mid = low  + ((high - low) / 2);
            if (sortedArray[mid] < key) {  // Check if the passed value is higher than the mid value or nut
                low = mid + 1;
            } else if (sortedArray[mid] > key) {
                high = mid - 1;
                System.out.println(high);
            } else if (sortedArray[mid] == key) {
                index = mid;
                break;
            }
        }
//        System.out.println(index);
        return index;
    }
}
