/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge26;

import java.lang.reflect.Array;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        int[] array = {8,4,23,42,16,15};
        App.sortArray(array);

    }

    public static int sortArray(int[] arr){

        for (int i=1; i< arr.length; i++){
            int temp= arr[i]; //i=4
            int k =i-1; //k= 3
            while (k>=0 && temp<arr[k]){
            arr[k+1]= arr[k]; //{8,4,23,42,16,15}
            k= k-1; //2
            }
            arr[k+1] = temp;
        }
        return arr[0];
    }
}
