/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge35;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void addNewVertex(){
        Graph graph = new Graph();
        Vertex vertex = new Vertex("Ali");

        assertEquals(vertex, graph.addVertex("Ali"));
    }

    @Test
    public void addNewEdge(){
        Graph graph = new Graph();
        graph.addVertex("Ibrahim");
        graph.addVertex("Ali");
        graph.addVertex("Ahmad");
        List<Vertex> list= new ArrayList<>();
        Vertex vertex=new Vertex("Ahmad");
        list.add(vertex);

        assertEquals(list , graph.addEdge("Ibrahim" , "Ahmad") );
    }
}
