/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package newCodeChallenges;

import org.checkerframework.checker.units.qual.A;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Methods methods = new Methods();

        //************************** Second Max ********************
        int[] arr1={-1 , -6 , -3 ,- 2};
        int secMax = methods.secondMax(arr1);
//        System.out.println(secMax);
        //**********************************************************

        //************************** Missing Number ****************
        int[] arr = {0, 6, 9, 12, 15};
        int missNum = methods.missingNumber(arr);
//        System.out.println(missNum);
        //************************************************************

        //************************ Have same char ********************
        String s1="aacb";
        String s2="abac";
        boolean b = methods.haveSameChar(s1, s2);
        System.out.println(b);
        //************************************************************
    }
}
