/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge15;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void add_contain_BinarySearch(){
        BinarySearchTree tree = new BinarySearchTree();
        tree.add(5);
        tree.add(8);
        tree.add(9);
        assertEquals( 3, tree.add(3));
        assertEquals( 5, tree.add(5));

        assertEquals(true , tree.contains(5));
        assertEquals(false , tree.contains(6));
        assertEquals(true , tree.contains(8));
    }

    @Test
    public void BinaryTree() {
        BinaryTree binaryTree = new BinaryTree();
        Node root = new Node(10);
        Node root1 = new Node(24);
        Node root3 = null;

      assertEquals( true ,binaryTree.pre_Order(root));
      assertEquals( false ,binaryTree.pre_Order(root3));

      assertEquals(false ,binaryTree.in_Order(root3) );
      assertEquals(true ,binaryTree.in_Order(root));

        ArrayList list = new ArrayList();
        list.add(24);
        list.add(10);
        binaryTree.post_Order(root1);
        assertEquals( list , binaryTree.post_Order(root));
    }

    @Test
    public void maxValue(){
        BinarySearchTree tree = new BinarySearchTree();
        tree.add(15);
        tree.add(8);
        tree.add(9);

        assertEquals(15 , tree.findMaxValue());

        tree.add(17);
        assertEquals(17 , tree.findMaxValue());
        tree.add(23);
        assertEquals(23 , tree.findMaxValue());
    }

    @Test public void breadthFirst(){
        BinarySearchTree binarySearchTree = new BinarySearchTree();
        Node root = new Node(5);
        root.left = new Node(7);
        root.left.left = new Node(14);
        root.right = new Node(3);
        root.right.right = new Node(8);
        ArrayList<Integer> list = new ArrayList();
        list.add(5);
        list.add(7);
        list.add(3);
        list.add(14);
        list.add(8);

        assertEquals( list, binarySearchTree.traverseLevelOrder(root));
    }

}
