/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge30;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        HashTable hashTable = new HashTable();
        hashTable.add("Ibrahim" , 8);
        hashTable.add("Ali" , 87);
        hashTable.add("kkk" , 65);
        hashTable.add("llll" , 14);
        hashTable.containsKey("kkk");
        hashTable.containsKey("Ali");
        hashTable.containsKey("Ibrahim");
        hashTable.containsKey("kkk");
        hashTable.get("Ali");
        System.out.println(hashTable.get("Ali"));

    }
}
