/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge35;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph graph = new Graph();
        graph.addVertex("Ibrahim");
        graph.addVertex("Ali");
        graph.addVertex("Ahmad");
        graph.addVertex("Osama");
        graph.addVertex("Omar");

        graph.addEdge("Ibrahim" , "Ali", 15);
        graph.addEdge("Ibrahim" , "Omar", 60 );
        graph.addEdge("Osama" , "Ali", 14);
        graph.addEdge("Omar" , "Ahmad", 30);

        Vertex vertex = new Vertex("Ibrahim");
//        System.out.println(graph.toString());

        graph.getSize();

        List list= new ArrayList();
        list.add("Ibrahim");
        list.add("Omar");
        list.add("Ahmad");

        System.out.println(graph.citiesTrip(graph, list));
    }
}
